### ISSUE TITLE
寻找源码的全类名问题

### ISSUE THREAD

**Issue by jiangwh** [NLPchina/Jcoder#3]
该项目中的代码需要格式化之后才能运行？

> 
public static String findClassName(String sourceCode) {

		try (BufferedReader br = new BufferedReader(new StringReader(sourceCode))) {
			String temp = null;

			while ((temp = br.readLine()) != null) {
				if (StringUtil.isBlank(temp)) {
					continue;
				}
				Matcher matcher = PAT.matcher(temp);

				if (matcher.find()) {
					temp = temp.split("[\\s+?;{]")[2];
					return temp;
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}

		return null;
	}
> 

针对都是一行的代码是无法找出正确的类名的。
如 ：
String code = "package com.test; public class     Test {public static void main(String[] args) {String hello = \"Hello World!!!\";System.out.println(hello);}}";
使用反捕获的方式可能是个不错的选择。

**Comment by ansjsun** [comment]
的确是由这个问题。。反射需要编译类，编译需要类名称。。。。不过可以通过代码分析拿到类名称。或者。通过完善的正则也可以。
话说用了很久没遇到不能编译的问题。所以暂且放过他了
